server.port: 8080

spring:
  application:
    name: api-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-login
              uri: lb://auth-service
              predicates:
                - Path=/login
              filters: [ ]

            - id: auth-service-register
              uri: lb://auth-service
              predicates:
                - Path=/register
              filters: [ ]

            - id: auth-service-csrf
              uri: lb://auth-service
              predicates:
                - Path=/csrf
              filters: [ ]

            - id: auth-service-secured
              uri: lb://auth-service
              predicates:
                - Path=/secured/**
              filters:
                - name: JwtAuthentication
logging:
  level:
    root: error

jwt:
  secret: vcNreNuHt307dFou/OD1Uc3w97+sLcJpi0nBsWbNK5czapXowy++EDOBbJ6AVBj1e+CxDL4d2M8YZlV5KNu2UA==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  base-uri: http://localhost:3000