server:
  port: 9000

spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: off

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_practise
    username: exist
    password: admin
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off

logging:
  level:
    root: error
    org.springframework.security: trace
    com.practise.security.infrastructure.security.filter.JwtAuthenticationFilter: trace
    com.practise.security.infrastructure.security.filter.JsonUsernamePasswordAuthFilter: trace
    com.practise.security.domain.service.AuthService: trace

  file:
    path: ./security/logs/auth-service.log

jwt:
  secret: vcNreNuHt307dFou/OD1Uc3w97+sLcJpi0nBsWbNK5czapXowy++EDOBbJ6AVBj1e+CxDL4d2M8YZlV5KNu2UA==
  expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
